name: Build and Deploy to Google Apps Script

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Set up service account credentials
        run: |
          echo '${{ secrets.CLASP_SERVICE_ACCOUNT_KEY }}' > service-account.json

      - name: Login to clasp with service account
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          clasp login --creds service-account.json

      - name: Push to Google Apps Script
        run: |
          clasp push
          clasp deploy
        env:
          CLASP_IGNORE: .claspignore 